# -*- coding: utf-8 -*-
"""Sales Performance Analysis Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvZei5pygo0bGhk-LpqGZNTAS0tN3E9u
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta

def generate_sales_data(num_records=10000):

    print(f"Generating synthetic dataset with {num_records} records...")

    categories = ['Technology', 'Office Supplies', 'Furniture']
    products = {
        'Technology': ['Laptop', 'Monitor', 'Smartphone', 'Webcam'],
        'Office Supplies': ['Pen', 'Paper', 'Binder', 'Stapler'],
        'Furniture': ['Chair', 'Table', 'Sofa', 'Bookcase']
    }

    end_date = datetime(2023, 12, 31)
    start_date = end_date - timedelta(days=364)
    dates = pd.to_datetime(start_date + (end_date - start_date) * np.random.rand(num_records))

    customer_ids = [f'CUST{i:04d}' for i in range(1, 1001)]
    customer_names = [f'Customer {i:04d}' for i in range(1, 1001)]
    customers = np.random.choice(customer_ids, num_records)

    data = []
    for i in range(num_records):
        order_id = f'ORD{i+1:05d}'
        category = np.random.choice(categories, p=[0.35, 0.40, 0.25])
        product = np.random.choice(products[category])
        sales = np.random.uniform(50, 1500)

        if category == 'Technology':
            profit = sales * np.random.uniform(0.18, 0.35)
        elif category == 'Office Supplies':
            profit = sales * np.random.uniform(0.05, 0.15)
        else:
            profit = sales * np.random.uniform(0.10, 0.20)

        month = dates[i].month
        if month in [11, 12]:
             sales *= np.random.uniform(1.2, 1.5)
             profit *= np.random.uniform(1.2, 1.3)

        data.append({
            'OrderID': order_id,
            'Customer ID': customers[i],
            'CustomerName': np.random.choice(customer_names),
            'Category': category,
            'Product': product,
            'Sales': sales,
            'Profit': profit,
            'OrderDate': dates[i]
        })

    df = pd.DataFrame(data)

    df.loc[np.random.choice(df.index, size=int(num_records * 0.005), replace=False), 'Sales'] = np.nan
    df.loc[np.random.choice(df.index, size=int(num_records * 0.003), replace=False), 'Profit'] = np.nan

    df['OrderDate'] = df['OrderDate'].astype(str)

    print("Data generation complete.")
    return df

df = generate_sales_data()

print("\nStarting Data Cleaning and Preprocessing...")

print(f"Records before cleaning: {len(df)}")
df.dropna(subset=['Sales', 'Profit'], inplace=True)
print(f"Records after dropping NaNs: {len(df)} (Missing rows handled)")

df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors='coerce')
df.dropna(subset=['OrderDate'], inplace=True)
print("Data types corrected (OrderDate to datetime).")

df['OrderMonth'] = df['OrderDate'].dt.month
df['OrderYearMonth'] = df['OrderDate'].dt.to_period('M')

print(f"Final records for analysis: {len(df)}")
print(f"Data types after cleaning:\n{df.dtypes}")

category_profit = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
most_profitable_category = category_profit.index[0]
print(f"\nAnalysis 1: Most Profitable Category is '{most_profitable_category}'")

monthly_sales = df.groupby('OrderMonth')['Sales'].sum()
peak_months = monthly_sales.sort_values(ascending=False).head(2)
peak_month_names = [datetime(2023, m, 1).strftime('%B') for m in peak_months.index]
print(f"Analysis 2: Peak Sales Months are {', '.join(peak_month_names)}")


customer_profitability = df.groupby('Customer ID')['Profit'].sum().sort_values(ascending=False).reset_index()
customer_profitability['Cumulative Profit'] = customer_profitability['Profit'].cumsum()
customer_profitability['Total Profit Share'] = customer_profitability['Cumulative Profit'] / customer_profitability['Profit'].sum()

total_customers = len(customer_profitability)
top_20_percent_count = int(total_customers * 0.20)
top_customers = customer_profitability.head(top_20_percent_count)
top_customer_profit_share = top_customers['Total Profit Share'].iloc[-1] * 100

print(f"\nAnalysis 3: Customer Segmentation (Pareto Analysis)")
print(f"Total Unique Customers: {total_customers}")
print(f"Top 20% Customers count: {top_20_percent_count}")
print(f"The top 20% of customers contribute to {top_customer_profit_share:.2f}% of total profit.")


print("\nGenerating Visualizations (sales_analysis_plots.png)...")
plt.style.use('fivethirtyeight')
fig, axes = plt.subplots(1, 2, figsize=(18, 7))
fig.suptitle('Key Sales Performance Metrics & Trends', fontsize=20, fontweight='bold', y=1.03)

sns.barplot(x=category_profit.index, y=category_profit.values, ax=axes[0], palette='viridis')
axes[0].set_title('Profit Contribution by Category', fontsize=14)
axes[0].set_ylabel('Total Profit (USD)')
axes[0].set_xlabel('Product Category')
axes[0].tick_params(axis='x', rotation=0)

month_order = list(range(1, 13))
monthly_sales_ordered = monthly_sales.reindex(month_order)
sns.lineplot(x=monthly_sales_ordered.index, y=monthly_sales_ordered.values, ax=axes[1], marker='o', color='crimson')
axes[1].set_title('Sales Volume Over the Year (Seasonality)', fontsize=14)
axes[1].set_ylabel('Total Sales (USD)')
axes[1].set_xlabel('Month Number')
axes[1].set_xticks(month_order)
axes[1].grid(True)
for month in peak_months.index:
    axes[1].axvline(x=month, color='orange', linestyle='--', linewidth=1.5, label='Peak Month' if month == peak_months.index[0] else "")

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.savefig('sales_analysis_plots.png')
print("Visualizations saved successfully as 'sales_analysis_plots.png'.")

print("\n" + "="*50)
print("BUSINESS RECOMMENDATIONS & KEY FINDINGS")
print("="*50)

print(f"1. Most Profitable Category: {most_profitable_category}")
print("   Recommendation (Inventory & Marketing): Increase inventory allocation and marketing spend on 'Technology' products. Investigate margins and costs in 'Office Supplies' to improve overall profitability.")

print(f"\n2. Peak Sales Season: {', '.join(peak_month_names)}")
print("   Recommendation (Marketing): Launch major promotional campaigns and secure optimal ad placements specifically targeting November and December, aligning with holiday shopping trends.")

print(f"\n3. Top Customer Contribution: {top_customer_profit_share:.2f}%")
print("   Recommendation (Retention Strategy): Develop a dedicated retention program (loyalty tiers, exclusive previews, personalized discounts) for the top 20% of customers to maximize their lifetime value.")

print("="*50)
print("Sales Performance Analysis script completed successfully.")